# the / route is defined via annotations

event_show:
    pattern:  /{slug}/show
    defaults: { _controller: "EventBundle:Event:show" }

event_new:
    pattern:  /new
    defaults: { _controller: "EventBundle:Event:new" }

event_create:
    pattern:  /create
    defaults: { _controller: "EventBundle:Event:create" }
    requirements: { _method: post }

event_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EventBundle:Event:edit" }

event_update:
    pattern:  /{id}/update
    defaults: { _controller: "EventBundle:Event:update" }
    requirements: { _method: post|put }

event_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EventBundle:Event:delete" }
    requirements: { _method: post|delete }
