parameters:
#    event.example.class: Yoda\EventBundle\Example

services:
    event_report_manager:
        class: Yoda\EventBundle\Reporting\EventReportManager
        arguments: ["@doctrine.orm.entity_manager", "@router"]
