security:
    encoders:
        Yoda\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EVENT_CREATE, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_database_users:
            entity: { class: UserBundle:User }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login_form
            logout:
                path:   logout
                target: event
            anonymous: ~
            switch_user: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
