_something_super_duper_crazy:
    resource: routing/default.yml

EventBundle_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    prefix:   /event

EventBundle_event_annotation:
    resource: "@EventBundle/Controller"
    prefix:   /event
    type:     annotation